jobs:
  main:
    requires: [~commit]
    image: docker:dind
    steps:
      - curl: |
          apk add git curl coreutils
          curl https://testfile.org/1.3GBiconpng  > ${SD_ARTIFACTS_DIR}/file1
